@WebApi_HostAddress = https://localhost:32769

POST {{WebApi_HostAddress}}/api/v2/boards
Content-Type: application/json
{
    "title": ""
}

###

GET {{WebApi_HostAddress}}/weatherforecast

###

POST {{WebApi_HostAddress}}/api/v1/boards
Content-Type: application/json

{
    "title": "a"
}

###
